services:
  - type: web
    name: nutrimart
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install "keras==3.4.1" "namex" "optree" "ml-dtypes" "rich"
    startCommand: gunicorn --config gunicorn.conf.py wsgi:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /tmp/nutrimart.db
